jobs:
  include:
  - stage: backend
    language: java
    script: echo Checking Env Vars... $BACKEND_JAR_FILENAME $FOO ; cd backend; ls -al; ./gradlew build; ls -al;

    #after_success: echo hello after success; git tag hello222; git push
    after_success: export TRAVIS_BACKEND_JAR="$(ls build/libs/*.jar)" ; echo $TRAVIS_BACKEND_JAR; export BACKEND_JAR="$(ls build/libs/*.jar)" ; echo $BACKEND_JAR ;  echo testing git branch... ; git branch

    before_deploy:
    - export TRAVIS_TAG="1.0.$TRAVIS_BUILD_NUMBER"
    - echo "$TRAVIS_TAG" "$TRAVIS_COMMIT"
    #- git config --local user.name "$USER_NAME"
    #- git config --local user.email "$USER_EMAIL"
    - git tag "$TRAVIS_TAG" "$TRAVIS_COMMIT"
    - export TRAVIS_COMMIT="My own defined value for this variable"
    - export TRAVIS_TAG="My own defined value for this variable"
    deploy:
      provider: releases
      tag_name: $TRAVIS_TAG
      target_commitish: $TRAVIS_COMMIT
      name: $TRAVIS_TAG
      api_key:
        secure: L3QEA6EGHS6Tu+/UJtVYeT9TGyvGpRLBO3d/A9whR8rujQuI91iekUPlzKS3DCo2fZwFaw+LilZ44QobmiPL4m13cRZPkyMJsH+6cYwpewOZkkjRvZaujHe/ha5L7YsLQGV16rCvfuSr/GiR78FE07UR/rceiXkLyn15YdMXWVRjUZcMMWitVmLVrxg6hpTvQM4BVEMQ9vOLOfeQxIoCCETwmgHbPM8G4qJKWsM9/fOcGthQk6xI3M33MRnZ29JRJhKzX3cMzmpRJ02jCVTvmDG7/zMeIhtie8HC1k4zYvpHft/2RtFTxc6A5EC1pycnle37H8gPYJKhHEhcDzW9kenD0YIXW13M3uv71fBswlU6PeBQQl/ShV4VLSo8vIXZleNGkGjM/1rTLbn8hFL0LC3O9eHTwhZY3ETSZRwBMRAQBLvaMBRtX/ZeK+9vBP1DZ79jNzpAzxNHoL/JiSXASqAm/d5ckzok6yl8NTQjEK+TjHmSOhrrJELhiRCoCRIpFEivX5qvm4O8rWov9toT2h3YITVeaLaTXsNRabr2AyglGQEgxwOQDaaMh2Seesp+dn2OgFeC0NNTI74QLpu2hF5CVvNjz/TszQ0YkewnVS1W3piI3UkyzoJ6jeR6ClXbdQmwE5PW3qmp8NHetw0y+DUFDOcYxeQMGCWWsBy9Np4=
      file_glob: true
      file: ./**/*.jar
      skip_cleanup: true
      # on:
      #   tags: true
      #   branches: 
      #     only:
      #     - master
      #     - add_cicd_scripts_practice

    # need to get a URL to the uploaded deploy artifact
  - stage: frontend
    language: objective-c
    xcode_project: frontend/Stickies.xcodeproj
    xcode_scheme: Stickies
    xcode_destination: platform=iOS Simulator,OS=11.4,name=iPhone X
    before_install: echo before_install , checking BACKEND_JAR $BACKEND_JAR checking TRAVIS_BACKEND_JAR $TRAVIS_BACKEND_JAR ; echo hello123;  curl -L https://github.com/integralio/stickies-ios/releases/download/$(echo $TRAVIS_TAG)/$BACKEND_JAR_FILENAME > backend.jar ;  ls -al;  java -jar backend.jar& ;  echo $TRAVIS_TAG;  echo $TRAVIS_COMMIT;
    after_script: curl localhost:8080/
