
jobs:
  include:
    - stage: backend
      language: java
      script: echo hello backend; cd backend; ls -al; ./gradlew check
    - stage: frontend
      language: objective-c
      xcode_project: frontend/Stickies.xcodeproj
      xcode_scheme: Stickies
      xcode_destination: platform=iOS Simulator,OS=11.4,name=iPhone X
